# Generated by Django 5.2.1 on 2025-05-29 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineas_Embotelladoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=200)),
                ('bph', models.FloatField()),
                ('Fecha_mantenimiento', models.DateField()),
                ('Temp_min', models.FloatField()),
                ('Temp_max', models.FloatField()),
                ('Uso_operativo', models.FloatField()),
                ('Criticidad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Botella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Cantidad', models.IntegerField()),
                ('Volumen', models.FloatField()),
                ('Envase', models.CharField(max_length=40)),
                ('Linea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Botellas', to='Reportes.lineas_embotelladoras')),
            ],
        ),
        migrations.CreateModel(
            name='Sabores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sabor', models.CharField(max_length=40)),
                ('Abrev', models.CharField(max_length=40)),
                ('Botella_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Botellas', to='Reportes.botella')),
            ],
        ),
    ]
