# Generated by Django 5.2.1 on 2025-05-30 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sabores',
            name='Botella_id',
        ),
    ]
