# Generated by Django 5.2.1 on 2025-05-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0002_remove_sabores_botella_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botella',
            name='Linea_id',
        ),
        migrations.AddField(
            model_name='botella',
            name='sabores',
            field=models.ManyToManyField(related_name='botellas', to='Reportes.sabores'),
        ),
        migrations.AddField(
            model_name='lineas_embotelladoras',
            name='botellas',
            field=models.ManyToManyField(related_name='lineas', to='Reportes.botella'),
        ),
    ]
