# Generated by Django 5.2.1 on 2025-05-30 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0003_remove_botella_linea_id_botella_sabores_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lineas_embotelladoras',
            name='usuarios',
            field=models.ManyToManyField(related_name='lineas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lineas_embotelladoras',
            name='Fecha_mantenimiento',
            field=models.CharField(max_length=50),
        ),
    ]
