# Generated by Django 5.2.1 on 2025-06-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0004_lineas_embotelladoras_usuarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botella',
            name='Cantidad',
        ),
        migrations.AddField(
            model_name='botella',
            name='Abre_envase',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botella',
            name='sabores',
            field=models.ManyToManyField(related_name='Botellas', to='Reportes.sabores'),
        ),
    ]
