# Generated by Django 5.2.1 on 2025-06-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0005_remove_botella_cantidad_botella_abre_envase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineas_embotelladoras',
            name='Presion_base',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineas_embotelladoras',
            name='Presion_maxima',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
