# Generated by Django 5.2.1 on 2025-05-29 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predice_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado_esperado', models.CharField(max_length=30)),
                ('Estado_calculado', models.CharField(max_length=30)),
                ('EstadoCalu', models.IntegerField()),
                ('Linea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios', to='Reportes.lineas_embotelladoras')),
                ('Usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
