# Generated by Django 5.2.1 on 2025-05-30 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Markov', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predice_estado',
            old_name='Estado_esperado',
            new_name='Estado_actual',
        ),
        migrations.AddField(
            model_name='predice_estado',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
