# Generated by Django 5.2.1 on 2025-05-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Markov', '0002_rename_estado_esperado_predice_estado_estado_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predice_estado',
            name='EstadoCalu',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='predice_estado',
            name='Estado_actual',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='predice_estado',
            name='Estado_calculado',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='predice_estado',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
