# Generated by Django 5.2.1 on 2025-05-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Markov', '0003_alter_predice_estado_estadocalu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predice_estado',
            name='EstadoCalu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predice_estado',
            name='Estado_actual',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='predice_estado',
            name='Estado_calculado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
