# Generated by Django 5.2.1 on 2025-05-29 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacion_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Acc_IA', models.CharField(max_length=40)),
                ('Acc_humana', models.CharField(max_length=40)),
                ('acc_final', models.CharField(max_length=40)),
                ('Invervencion', models.BooleanField()),
                ('Temperatura', models.FloatField()),
                ('Presion', models.FloatField()),
                ('Uso', models.FloatField()),
                ('Recompensa', models.FloatField()),
                ('Comentario', models.CharField(max_length=200)),
                ('Linea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lineas_Simulacion', to='Reportes.lineas_embotelladoras')),
                ('Usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
