# Generated by Django 5.2.1 on 2025-05-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Acc_IA',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Acc_humana',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Comentario',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Invervencion',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Presion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Recompensa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Temperatura',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Uso',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='acc_final',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
