# Generated by Django 5.2.1 on 2025-05-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_learning', '0002_alter_simulacion_estado_acc_ia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Acc_IA',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Acc_humana',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Comentario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Invervencion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Presion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Recompensa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='Uso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulacion_estado',
            name='acc_final',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
